name: Build and Deploy Docs Branch

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # Checkout main
      - name: Checkout main
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build project
      - name: Build project
        run: pnpm exec rsbuild build

      # Replace docs
      - name: Replace docs
        run: |
          rm -rf docs
          mv dist docs

      # Create CNAME file
      - name: Create CNAME file
        run: |
          echo "$CNAME_DOMAIN" > docs/CNAME
        env:
          CNAME_DOMAIN: ${{ secrets.CNAME_DOMAIN }}

      # Commit & push to dedicated branch
      - name: Commit & push to dedicated branch
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B docs-folder-update
          git add docs
          git commit -m "feat: generated new /docs folder" || echo "No changes to commit"
          git push -u origin docs-folder-update --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}