name: Deploy Docs on Main

# Trigger when main branch is updated (PR merged)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout main branch
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install pnpm
      - run: npm install -g pnpm

      # 4. Install dependencies
      - run: pnpm install --frozen-lockfile

      # 5. Build project using rsbuild
      - run: pnpm exec rsbuild build

      # 6. Replace /docs with the build output
      - run: |
          rm -rf docs
          mv dist docs

      # 7. Commit and push /docs to main
      - run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update docs folder [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}