name: PR Checks

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'docs/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v3

      # Clean /docs folder
      - name: Clean /docs folder
        run: rm -rf docs

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Run typecheck
      - name: Run typecheck
        run: pnpm typecheck

      # Run lint
      - name: Run lint
        run: pnpm lint

      # Build project
      - name: Build project
        run: pnpm exec rsbuild build

      # Replace docs
      - name: Replace docs
        run: mv dist docs

      # Create CNAME file
      - name: Create CNAME file
        run: |
          echo "$CNAME_DOMAIN" > docs/CNAME
        env:
          CNAME_DOMAIN: ${{ secrets.CNAME_DOMAIN }}

      # Pull latest changes, bump package version, and commit all changes
      - name: Pull latest changes, commit, and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin ${{ github.head_ref }}
          npm version patch --no-git-tag-version
          git add package.json pnpm-lock.yaml docs
          git commit -m "chore: bump version and update docs to $(node -p "require('./package.json').version")" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}