name: PR Checks

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.filter.outputs.docs }}
    steps:
      # Checkout PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v3

      # Check if docs/** files were changed
      - name: Filter file changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            docs:
              - 'docs/**'

  build-test-lint:
    runs-on: ubuntu-latest
    needs: check-files

    steps:
      # Checkout PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Run typecheck
      - name: Run typecheck
        if: needs.check-files.outputs.docs_changed == 'false'
        run: pnpm typecheck

      # Run lint
      - name: Run lint
        run: pnpm lint

      # Clean /docs folder
      - name: Clean /docs folder
        if: needs.check-files.outputs.docs_changed == 'false'
        run: rm -rf docs

      # Build project
      - name: Build project
        if: needs.check-files.outputs.docs_changed == 'false'
        run: pnpm exec rsbuild build

      # Replace docs
      - name: Replace docs
        if: needs.check-files.outputs.docs_changed == 'false'
        run: mv dist docs

      # Create CNAME file
      - name: Create CNAME file
        if: needs.check-files.outputs.docs_changed == 'false'
        run: |
          echo "$CNAME_DOMAIN" > docs/CNAME
        env:
          CNAME_DOMAIN: ${{ secrets.CNAME_DOMAIN }}

      # Pull latest changes, bump version, and push all changes
      - name: Pull latest changes, bump version, and push
        if: needs.check-files.outputs.docs_changed == 'false'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin $BRANCH_NAME
          npm version patch --no-git-tag-version
          git add package.json pnpm-lock.yaml docs
          git commit -m "chore: bump version and update docs to $(node -p "require('./package.json').version")" || echo "No changes to commit"
          git push origin HEAD:$BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref }}