name: PR Checks

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout PR branch
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install pnpm
      - run: npm install -g pnpm

      # Install dependencies
      - run: pnpm install --frozen-lockfile

      # Build project with rsbuild
      - run: pnpm exec rsbuild build

      # Run typecheck and lint
      - run: pnpm typecheck
      - run: pnpm lint